language: julia
os:
    - linux
julia:
    - release
    - nightly
    - 0.5.2
before_script:
    - julia --color=yes -e 'Pkg.clone(pwd())'
    - julia --color=yes -e 'Pkg.add("Coverage")'
    - julia --color=yes -e 'Pkg.add("Documenter")'
    - julia --color=yes -e 'Pkg.add("Lint")'
script:
    - julia --color=yes -e 'Pkg.build("Materials")'
    - julia --color=yes -e 'Pkg.test("Materials", coverage=true)'
    - julia --color=yes -e 'cd(Pkg.dir("Materials", "test")); include("run_lint.jl")'
    - julia --color=yes -e 'cd(Pkg.dir("Materials", "docs")); include("make.jl")'
after_success:
    - julia --color=yes -e 'cd(Pkg.dir("Materials")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    - julia --color=yes -e 'cd(Pkg.dir("Materials", "docs")); include("deploy.jl")'
