name = "Materials"
uuid = "35fa313e-aa48-52ea-bc82-ddb91c7db87b"
version = "0.4.0"

[deps]
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
julia = "1.0.0"
Einsum = "0.4.1"
ForwardDiff = "0.10.3"
NLsolve = "4.1.0"
Parameters = "0.12.0"
Tensors = "1.2.0"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "Test"]
